// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package account_point

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	MarkId               string   `protobuf:"bytes,2,opt,name=MarkId,proto3" json:"MarkId,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=Uid,proto3" json:"Uid,omitempty"`
	AppId                string   `protobuf:"bytes,4,opt,name=AppId,proto3" json:"AppId,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=Username,proto3" json:"Username,omitempty"`
	Account              string   `protobuf:"bytes,6,opt,name=Account,proto3" json:"Account,omitempty"`
	UserLevel            int32    `protobuf:"varint,7,opt,name=UserLevel,proto3" json:"UserLevel,omitempty"`
	Verified             int32    `protobuf:"varint,8,opt,name=Verified,proto3" json:"Verified,omitempty"`
	Avatar               string   `protobuf:"bytes,9,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	CompanyId            string   `protobuf:"bytes,10,opt,name=CompanyId,proto3" json:"CompanyId,omitempty"`
	Position             string   `protobuf:"bytes,11,opt,name=Position,proto3" json:"Position,omitempty"`
	Area                 string   `protobuf:"bytes,12,opt,name=Area,proto3" json:"Area,omitempty"`
	Phone                string   `protobuf:"bytes,13,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Sex                  int32    `protobuf:"varint,14,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Email                string   `protobuf:"bytes,15,opt,name=Email,proto3" json:"Email,omitempty"`
	InviteCode           string   `protobuf:"bytes,16,opt,name=InviteCode,proto3" json:"InviteCode,omitempty"`
	DeviceToken          string   `protobuf:"bytes,17,opt,name=DeviceToken,proto3" json:"DeviceToken,omitempty"`
	DepositAddress       string   `protobuf:"bytes,18,opt,name=DepositAddress,proto3" json:"DepositAddress,omitempty"`
	PublicKey            string   `protobuf:"bytes,19,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	PrivateKey           string   `protobuf:"bytes,20,opt,name=PrivateKey,proto3" json:"PrivateKey,omitempty"`
	Device               string   `protobuf:"bytes,21,opt,name=Device,proto3" json:"Device,omitempty"`
	CreateTime           int64    `protobuf:"varint,22,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	RegVersion           string   `protobuf:"bytes,23,opt,name=RegVersion,proto3" json:"RegVersion,omitempty"`
	NowVersion           string   `protobuf:"bytes,24,opt,name=NowVersion,proto3" json:"NowVersion,omitempty"`
	CloseUntil           int64    `protobuf:"varint,25,opt,name=CloseUntil,proto3" json:"CloseUntil,omitempty"`
	SuperUserLevel       int32    `protobuf:"varint,26,opt,name=SuperUserLevel,proto3" json:"SuperUserLevel,omitempty"`
	Identification       int32    `protobuf:"varint,27,opt,name=Identification,proto3" json:"Identification,omitempty"`
	IdentificationInfo   string   `protobuf:"bytes,28,opt,name=IdentificationInfo,proto3" json:"IdentificationInfo,omitempty"`
	IsSetPayPwd          int32    `protobuf:"varint,29,opt,name=IsSetPayPwd,proto3" json:"IsSetPayPwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ac7e387cca4cbe38, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetMarkId() string {
	if m != nil {
		return m.MarkId
	}
	return ""
}

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *User) GetUserLevel() int32 {
	if m != nil {
		return m.UserLevel
	}
	return 0
}

func (m *User) GetVerified() int32 {
	if m != nil {
		return m.Verified
	}
	return 0
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *User) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *User) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

func (m *User) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

func (m *User) GetDepositAddress() string {
	if m != nil {
		return m.DepositAddress
	}
	return ""
}

func (m *User) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *User) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *User) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetRegVersion() string {
	if m != nil {
		return m.RegVersion
	}
	return ""
}

func (m *User) GetNowVersion() string {
	if m != nil {
		return m.NowVersion
	}
	return ""
}

func (m *User) GetCloseUntil() int64 {
	if m != nil {
		return m.CloseUntil
	}
	return 0
}

func (m *User) GetSuperUserLevel() int32 {
	if m != nil {
		return m.SuperUserLevel
	}
	return 0
}

func (m *User) GetIdentification() int32 {
	if m != nil {
		return m.Identification
	}
	return 0
}

func (m *User) GetIdentificationInfo() string {
	if m != nil {
		return m.IdentificationInfo
	}
	return ""
}

func (m *User) GetIsSetPayPwd() int32 {
	if m != nil {
		return m.IsSetPayPwd
	}
	return 0
}

type UserReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ac7e387cca4cbe38, []int{1}
}
func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (dst *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(dst, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "account.point.User")
	proto.RegisterType((*UserReq)(nil), "account.point.UserReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSrvClient is the client API for UserSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSrvClient interface {
	// get user info.
	UserInfo(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*User, error)
}

type userSrvClient struct {
	cc *grpc.ClientConn
}

func NewUserSrvClient(cc *grpc.ClientConn) UserSrvClient {
	return &userSrvClient{cc}
}

func (c *userSrvClient) UserInfo(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/account.point.UserSrv/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSrvServer is the server API for UserSrv service.
type UserSrvServer interface {
	// get user info.
	UserInfo(context.Context, *UserReq) (*User, error)
}

func RegisterUserSrvServer(s *grpc.Server, srv UserSrvServer) {
	s.RegisterService(&_UserSrv_serviceDesc, srv)
}

func _UserSrv_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.point.UserSrv/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).UserInfo(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.point.UserSrv",
	HandlerType: (*UserSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserInfo",
			Handler:    _UserSrv_UserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_ac7e387cca4cbe38) }

var fileDescriptor_api_ac7e387cca4cbe38 = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x4f, 0x6f, 0x1a, 0x31,
	0x10, 0xc5, 0x4b, 0x12, 0x20, 0x38, 0x0d, 0x4d, 0x9d, 0x94, 0x4e, 0x68, 0x5a, 0x21, 0x0e, 0x15,
	0x27, 0x0e, 0xed, 0xa9, 0x47, 0x04, 0x3d, 0xac, 0xfa, 0x47, 0x2b, 0x08, 0xb9, 0x3b, 0x78, 0x68,
	0xad, 0x80, 0xbd, 0xf5, 0x9a, 0x4d, 0xf9, 0x9e, 0xfd, 0x40, 0xd5, 0x8c, 0x81, 0x85, 0x28, 0x27,
	0xfc, 0x7e, 0x6f, 0x76, 0x78, 0x33, 0xbb, 0x16, 0x0d, 0x95, 0x99, 0x7e, 0xe6, 0x5d, 0x70, 0xf2,
	0x5c, 0xcd, 0x66, 0x6e, 0x65, 0x43, 0x3f, 0x73, 0xc6, 0x86, 0xee, 0xbf, 0x9a, 0x38, 0x99, 0xe6,
	0xe8, 0x65, 0x4b, 0xd4, 0xe8, 0x37, 0xd1, 0x50, 0xe9, 0x54, 0x7a, 0x8d, 0xf1, 0x46, 0x11, 0xff,
	0xa1, 0xfc, 0x43, 0xa2, 0xe1, 0x28, 0xf2, 0xa8, 0xe4, 0x85, 0x38, 0x9e, 0x1a, 0x0d, 0xc7, 0x0c,
	0xe9, 0x28, 0xaf, 0x44, 0x75, 0x90, 0x65, 0x89, 0x86, 0x13, 0x66, 0x51, 0xc8, 0xb6, 0x38, 0xa5,
	0x4e, 0x56, 0x2d, 0x11, 0xaa, 0x6c, 0xec, 0xb4, 0x04, 0x51, 0x1f, 0xc4, 0x34, 0x50, 0x63, 0x6b,
	0x2b, 0xe5, 0x8d, 0x68, 0x50, 0xd5, 0x77, 0x2c, 0x70, 0x01, 0xf5, 0x4e, 0xa5, 0x57, 0x1d, 0x97,
	0x80, 0x7a, 0xde, 0xa1, 0x37, 0x73, 0x83, 0x1a, 0x4e, 0xd9, 0xdc, 0x69, 0xca, 0x3b, 0x28, 0x54,
	0x50, 0x1e, 0x1a, 0x31, 0x6f, 0x54, 0xd4, 0x71, 0xe8, 0x96, 0x99, 0xb2, 0xeb, 0x44, 0x83, 0x60,
	0xab, 0x04, 0xd4, 0x31, 0x75, 0xb9, 0x09, 0xc6, 0x59, 0x38, 0x8b, 0x29, 0xb7, 0x5a, 0x4a, 0x71,
	0x32, 0xf0, 0xa8, 0xe0, 0x25, 0x73, 0x3e, 0xd3, 0xac, 0xe9, 0x6f, 0x67, 0x11, 0xce, 0xe3, 0xac,
	0x2c, 0x68, 0x27, 0x13, 0xfc, 0x0b, 0x4d, 0x8e, 0x44, 0x47, 0xaa, 0xfb, 0xba, 0x54, 0x66, 0x01,
	0xaf, 0x62, 0x1d, 0x0b, 0xf9, 0x41, 0x88, 0xc4, 0x16, 0x26, 0xe0, 0xd0, 0x69, 0x84, 0x0b, 0xb6,
	0xf6, 0x88, 0xec, 0x88, 0xb3, 0x11, 0x16, 0x66, 0x86, 0xb7, 0xee, 0x01, 0x2d, 0xbc, 0xe6, 0x82,
	0x7d, 0x24, 0x3f, 0x8a, 0xe6, 0x08, 0x33, 0x4a, 0x38, 0xd0, 0xda, 0x63, 0x9e, 0x83, 0xe4, 0xa2,
	0x27, 0x94, 0xa6, 0x4e, 0x57, 0xf7, 0x0b, 0x33, 0xfb, 0x86, 0x6b, 0xb8, 0x8c, 0x53, 0xef, 0x00,
	0xe5, 0x48, 0xbd, 0x29, 0x54, 0x40, 0xb2, 0xaf, 0x62, 0x8e, 0x92, 0xd0, 0x2e, 0xe3, 0x9f, 0xc2,
	0x9b, 0xb8, 0xcb, 0xa8, 0xe8, 0xb9, 0xa1, 0x47, 0x15, 0xf0, 0xd6, 0x2c, 0x11, 0x5a, 0x9d, 0x4a,
	0xef, 0x78, 0xbc, 0x47, 0xc8, 0x1f, 0xe3, 0xaf, 0x3b, 0xf4, 0x39, 0xed, 0xf3, 0x6d, 0xec, 0x5b,
	0x12, 0xf2, 0x7f, 0xba, 0xc7, 0xad, 0x0f, 0xd1, 0x2f, 0x09, 0xf7, 0x5f, 0xb8, 0x1c, 0xa7, 0x36,
	0x98, 0x05, 0x5c, 0x6f, 0xfa, 0xef, 0x08, 0x4d, 0x3f, 0x59, 0x65, 0xe8, 0xcb, 0x4f, 0xa4, 0xcd,
	0x2b, 0x7f, 0x42, 0xa9, 0x2e, 0xd1, 0x68, 0x83, 0x99, 0x9b, 0x99, 0xe2, 0x77, 0xfb, 0x2e, 0xd6,
	0x1d, 0x52, 0xd9, 0x17, 0xf2, 0x90, 0x24, 0x76, 0xee, 0xe0, 0x86, 0x73, 0x3d, 0xe3, 0xd0, 0xfb,
	0x49, 0xf2, 0x09, 0x86, 0x54, 0xad, 0xd3, 0x47, 0x0d, 0xef, 0xb9, 0xe9, 0x3e, 0xea, 0x5e, 0x8b,
	0x3a, 0xc5, 0x18, 0xe3, 0x1f, 0xd9, 0x14, 0x47, 0x66, 0x7b, 0xa9, 0x8e, 0x8c, 0xfe, 0x34, 0x8a,
	0xd6, 0xc4, 0x17, 0xf2, 0x4b, 0xbc, 0x1b, 0xdc, 0xb3, 0xd5, 0x3f, 0xb8, 0x98, 0xfd, 0xcd, 0xe3,
	0xed, 0xcb, 0x67, 0x78, 0xf7, 0xc5, 0x7d, 0x8d, 0x6f, 0xf3, 0xe7, 0xff, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xf4, 0xee, 0xaf, 0x58, 0xda, 0x03, 0x00, 0x00,
}
