[server]
addr="0.0.0.0:8190"

[authServer]
host="http://127.0.0.1:8190"

[mysql]
#host="127.0.0.1"
#port=3306
#user="root"
#pwd="123456"
#db="work"
host="172.16.103.31"
port=3306
user="root"
pwd="123"
db="work"

[redis]
url="redis://127.0.0.1:6379"
#password="123456"
maxIdle=30
maxActive=50
idleTimeout=240

[chat33Server]
host="http://172.16.103.31:8088/chat"

[work33]
host="http://192.168.101.239:8082"
token=""

[log]
level="debug"