// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package micro_cli

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_553cf6ab673994c5, []int{0}
}
func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (dst *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(dst, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=Uid,proto3" json:"Uid,omitempty"`
	AppId                string   `protobuf:"bytes,4,opt,name=AppId,proto3" json:"AppId,omitempty"`
	EndTime              int64    `protobuf:"varint,5,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_553cf6ab673994c5, []int{1}
}
func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (dst *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(dst, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AuthResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AuthResponse) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "AuthResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_553cf6ab673994c5) }

var fileDescriptor_api_553cf6ab673994c5 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe4, 0xe2, 0x76, 0x2c, 0x2d, 0xc9, 0x08, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0x4d, 0x2c, 0x28, 0xf0, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x40, 0xa2, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0x4c, 0x10,
	0x51, 0x30, 0x47, 0xa9, 0x8e, 0x8b, 0x07, 0xa2, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48,
	0x8c, 0x8b, 0x2d, 0xb4, 0x38, 0xb5, 0x08, 0xae, 0x19, 0xca, 0x03, 0xe9, 0x0e, 0x41, 0xd6, 0x0d,
	0xe6, 0x08, 0x09, 0x70, 0x31, 0x87, 0x66, 0xa6, 0x48, 0x30, 0x83, 0xc5, 0x40, 0x4c, 0x90, 0x3a,
	0x47, 0xb0, 0xdd, 0x2c, 0x10, 0x75, 0x60, 0x8e, 0x90, 0x04, 0x17, 0xbb, 0x6b, 0x5e, 0x4a, 0x48,
	0x66, 0x6e, 0xaa, 0x04, 0xab, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x8c, 0x6b, 0x64, 0xcc, 0xc5, 0xe5,
	0x9a, 0x57, 0x92, 0x5a, 0x54, 0x50, 0x94, 0x59, 0x9c, 0x2a, 0xa4, 0xca, 0xc5, 0x02, 0x72, 0x8d,
	0x10, 0x8f, 0x1e, 0x92, 0x7f, 0xa4, 0x78, 0xf5, 0x90, 0x9d, 0xa8, 0xc4, 0x90, 0xc4, 0x06, 0xf6,
	0xb6, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x52, 0x91, 0x15, 0x2c, 0x03, 0x01, 0x00, 0x00,
}
